---
- name: install pillow
  become: true
  apt:
    name: python3-pil
  
- name: install django
  pip:
    name: "{{item}}"
    virtualenv: "{{VENV}}"
  with_items:
    - django
    - django-storages
    - djangorestframework
    - gunicorn

- name: install nginx
  become: true
  apt:
    name: nginx

- name: install supervisor
  become: true
  apt:
    name: supervisor

- name: install postgresql
  become: true
  apt:
    name: "{{item}}"
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - postgresql-client
    - postgresql-client-common

- name: install psycopg2
  pip:
    name: psycopg2
    virtualenv: "{{VENV}}"

- name: copy nginx setting
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{WWW_SERVER_NAME}}"
    force: true

- name: create simbolic link
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{WWW_SERVER_NAME}}"
    dest: "/etc/nginx/sites-enabled/{{WWW_SERVER_NAME}}"
    state: link

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: copy start_gunicorn.sh
  template:
    src: start_gunicorn.sh.j2
    dest: "{{DJANGO_PROJECT_HOME}}/start.sh"
    mode: 0755
    force: true
    
- name: copy supervisord conf
  become: yes
  template:
    src: supervisord.conf.j2
    dest: "/etc/supervisor/conf.d/{{DJANGO_PROJECT_NAME}}.conf"

- name: restart supervisord
  become: yes
  service:
    name: supervisor
    state: reloaded