---
- name: Check if mecab is installed
  command: which mecab
  ignore_errors: True
  register: is_mecab_installed

- stat:
    path: /tmp/mecab
  register: is_mecab_cloned
  when: is_mecab_installed | failed

- name: Clone Mecab
  git:
    repo: https://github.com/taku910/mecab.git
    dest: /tmp/mecab
  when: (is_mecab_installed | failed) and (not is_mecab_cloned.stat.exists)
  ignore_errors: True

- name: configure, make MeCab
  command: "{{item}}"
  args:
    chdir: /tmp/mecab/mecab
  with_items:
    - './configure'
    - 'make'
  when: is_mecab_installed | failed

- name: make install MeCab
  become: yes
  command: "make install"
  args:
    chdir: /tmp/mecab/mecab
  when: is_mecab_installed | failed

- name: make ipadic for MeCab
  command: "{{item}}"
  args:
    chdir: /tmp/mecab/mecab-ipadic
  with_items:
    - "./configure"
    - "make"
  when: is_mecab_installed | failed

- name: make install ipadic for MeCab
  become: yes
  command: "make install"
  args:
    chdir: /tmp/mecab/mecab-ipadic
  when: is_mecab_installed | failed
